CREATE DATABASE catmash;

CREATE TABLE `catmash`.`cat` (
  `SCORE` INT NULL,
  `URL` VARCHAR(45) NULL,
  `ID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`));
  
ALTER TABLE `catmash`.`cat` 
CHANGE COLUMN `URL` `URL` LONGBLOB NULL DEFAULT NULL ;
